# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Build HTMLZip
formats:
  - htmlzip

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: doc/conf.py

# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
  - requirements: doc/requirements.txt
