{
  "revision": "20180117",
  "documentationLink": "https://developers.google.com/slides/",
  "id": "slides:v1",
  "discoveryVersion": "v1",
  "version_module": true,
  "protocol": "rest",
  "canonicalName": "Slides",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/spreadsheets": {
          "description": "View and manage your spreadsheets in Google Drive"
        },
        "https://www.googleapis.com/auth/presentations": {
          "description": "View and manage your Google Slides presentations"
        },
        "https://www.googleapis.com/auth/presentations.readonly": {
          "description": "View your Google Slides presentations"
        },
        "https://www.googleapis.com/auth/drive.file": {
          "description": "View and manage Google Drive files and folders that you have opened or created with this app"
        },
        "https://www.googleapis.com/auth/spreadsheets.readonly": {
          "description": "View your Google Spreadsheets"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "View and manage the files in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive.readonly": {
          "description": "View the files in your Google Drive"
        }
      }
    }
  },
  "rootUrl": "https://slides.googleapis.com/",
  "ownerDomain": "google.com",
  "name": "slides",
  "batchPath": "batch",
  "title": "Google Slides API",
  "ownerName": "Google",
  "resources": {
    "presentations": {
      "methods": {
        "get": {
          "flatPath": "v1/presentations/{presentationsId}",
          "path": "v1/presentations/{+presentationId}",
          "id": "slides.presentations.get",
          "description": "Gets the latest version of the specified presentation.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly",
            "https://www.googleapis.com/auth/presentations",
            "https://www.googleapis.com/auth/presentations.readonly"
          ]
        },
        "create": {
          "flatPath": "v1/presentations",
          "path": "v1/presentations",
          "id": "slides.presentations.create",
          "description": "Creates a new presentation using the title given in the request. Other\nfields in the request are ignored.\nReturns the created presentation.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/presentations"
          ]
        },
        "batchUpdate": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly",
            "https://www.googleapis.com/auth/presentations",
            "https://www.googleapis.com/auth/spreadsheets",
            "https://www.googleapis.com/auth/spreadsheets.readonly"
          ],
          "flatPath": "v1/presentations/{presentationId}:batchUpdate",
          "path": "v1/presentations/{presentationId}:batchUpdate",
          "id": "slides.presentations.batchUpdate",
          "description": "Applies one or more updates to the presentation.\n\nEach request is validated before\nbeing applied. If any request is not valid, then the entire request will\nfail and nothing will be applied.\n\nSome requests have replies to\ngive you some information about how they are applied. Other requests do\nnot need to return information; these each return an empty reply.\nThe order of replies matches that of the requests.\n\nFor example, suppose you call batchUpdate with four [...]"
        }
      },
      "resources": {
        "pages": {
          "methods": {
            "get": {
              "description": "Gets the latest version of the specified page in the presentation.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/drive.readonly",
                "https://www.googleapis.com/auth/presentations",
                "https://www.googleapis.com/auth/presentations.readonly"
              ],
              "flatPath": "v1/presentations/{presentationId}/pages/{pageObjectId}",
              "id": "slides.presentations.pages.get",
              "path": "v1/presentations/{presentationId}/pages/{pageObjectId}"
            },
            "getThumbnail": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/drive.readonly",
                "https://www.googleapis.com/auth/presentations",
                "https://www.googleapis.com/auth/presentations.readonly"
              ],
              "flatPath": "v1/presentations/{presentationId}/pages/{pageObjectId}/thumbnail",
              "path": "v1/presentations/{presentationId}/pages/{pageObjectId}/thumbnail",
              "id": "slides.presentations.pages.getThumbnail",
              "description": "Generates a thumbnail of the latest version of the specified page in the\npresentation and returns a URL to the thumbnail image."
            }
          }
        }
      }
    }
  },
  "version": "v1",
  "baseUrl": "https://slides.googleapis.com/",
  "servicePath": "",
  "description": "An API for creating and editing Google Slides presentations.",
  "kind": "discovery#restDescription",
  "basePath": ""
}
